### PR TITLE
Chatdev now supports GPT_4o 

### PR DESCRIPTION
**Pull request by rizzleroc**
Update all files for support of the new model that was released gpt_4o_05-13-2024

### CODE REVIEW

**Comment by rizzleroc** [comment]
You will also need to get the most recent version of the tiktoken uninstall and reinstall version=0.7.0

**Comment by djbritt** [comment]
Please add support for gpt_4o!!

**Comment by javidmardanov** [comment]
Thanks! Do you know how can I select the agents' default model?

**Comment by thinkwee** [comment]
Thank you! We have added support to GPT4O in https://github.com/OpenBMB/ChatDev/pull/404

**Pull request closed without merging**
