### PR TITLE
Added Docker Support

### PR DESCRIPTION
**Pull request by ManindraDeMel**
# Docker Integration for the Project #125 

## Changes Made

- **Dockerfile Creation**: Introduced a Dockerfile to containerize the project. This makes it easier for contributors and users to set up the project without worrying about dependencies.

- **Flask App Updates**: Updated the Flask app to bind to `0.0.0.0` allowing it to be accessed outside of the container. Additionally, modified the port configuration using argparse for flexibility.

## Building the Docker Container

Before running the application, you'll need to build the Docker container. To do this, navigate to the directory containing the Dockerfile and run:

```bash
docker build -t chatdev:latest .
```

This command will build a Docker image using the provided Dockerfile and tag it as `chatdev:latest`.

## How to Run the Docker Container

To run the containerized application, use the following command:

```bash
docker run -it --rm -p 8000:8000 -e OPENAI_API_KEY=your_openai_api_key chatdev:latest
```

Replace `your_openai_api_key` with your actual OpenAI API key.

Once you have it running you can run the project as if it were your local system

## Copying Files out of Docker

If you wish to copy files out of the Docker container and into the host machine, you can use the `docker cp` command. This can be handy, especially when chatdev finishes and you wish to upload the generated files into the webapp to be reviewed.

```bash
docker cp container_id:/path/in/container /path/on/host
```

## Docker Image Pull Command

To pull the current Docker image (under my personal account), use:

```bash
docker pull manindrademel/chatdev:latest
```

## Suggestion for Project Maintainers

It would be beneficial to set up a Docker account specific to this project. This way, the Docker image can reside under a more general name rather than an individual's account. I would be happy to assist in pushing the image to such an account once it's set up.

## Additional Notes

The webserver in `online_log/app.py` will still be accessible on your local machine as we have exposed the http port on docker for this purpose.

---

Thank you for considering this integration. Looking forward to feedback!

### CODE REVIEW

**Review by superseppl — APPROVED** [review]
Looks good and works!

**Review by thinkwee — APPROVED** [review]

**Comment by thinkwee** [comment]
Thank you for your contribution! I will make some modifications so that in the docker ChatDev can run GUI software.

**Comment by gerardsyd** [comment]
can this be run in a headless environment or does it need a display and therefore cannot be run headless?

**Comment by ManindraDeMel** [comment]
> can this be run in a headless environment or does it need a display and therefore cannot be run headless?

Yes it can be run headless

**Pull request merged**
