### PR TITLE
tiny_rogue_like

### PR DESCRIPTION
**Pull request by GeekyWizKid**
This is a simple abstract runnable roguelike game based on GPT3.5

### CODE REVIEW

**Comment by GeekyWizKid** [comment]
I only adjusted the width and height of the user pixel in the game and left the rest of the code untouched, it's amazing!

**Comment by dhustler98** [comment]
how can i start guys bany help am new here

**Comment by GeekyWizKid** [comment]
> how can i start guys bany help am new here

I'm not quite sure what you want.
If you are trying to generate a project you can do that:
1. apply for a chatGPT account and get its API Key
2. fork and clone the project
3. Read the readme for the project, which contains instructions and a video.
4. Have an idea
5. Most importantly, get your hands dirty.

**Comment by thinkwee** [comment]
@NA-Wen please check the replay part

**Comment by NA-Wen** [comment]
lgtm

**Review by thinkwee — APPROVED** [review]

**Comment by thinkwee** [comment]
Thank you for your contribution! You are the first one to share software! I will mark the status of this roguelike game as ``Biased`` since GPT does not fulfill all the requirements in your query and manual, such as the player does not enter the next level when touching a door and there is no monster, but it is a great try!

**Pull request merged**
